repos:
  - repo: local
    hooks:
      # black for python files
      - id: black
        name: black
        entry: black
        language: system
        types: [python]

      # flake8 for python files
      - id: flake8
        name: flake8
        entry: flake8
        language: system
        types: [ python ]
        args: [ "--max-line-length=100", "--ignore=E203, W503" ]

      # isort for python files
      - id: isort
        name: isort
        entry: isort
        language: system
        types: [python]
        args: ["--profile=black", "--filter-files", "-m=3"]