services:
  backend:
    build: 
      dockerfile: ./docker/backend.Dockerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - app-network
    command: poetry run python3 src/main.py

  frontend:
    build: 
      dockerfile: ./docker/frontend.Dockerfile
    container_name: frontend
    ports:
      - "7860:7860"
    depends_on:
      - backend
    networks:
      - app-network
    command: poetry run python3 src/main.py

networks:
  app-network:
    driver: bridge